labels:
  - name: "ci/cd"
    color: "1D76DB"
    description: "CI/CD process related issues"
  - name: "pipeline-failure"
    color: "D93F0B"
    description: "Indicates a failed automation or workflow run"
  - name: "automation"
    color: "5319E7"
    description: "Automation, scripting, or bot-related"
  - name: "severity-high"
    color: "B60205"
    description: "High severity CI/CD event or failure"
  - name: "needs-investigation"
    color: "FFD700"
    description: "Requires debugging or triage"
  - name: "bug"
    color: "D73A4A"
    description: "A bug or unexpected error"
  - name: "enhancement"
    color: "A2EEEF"
    description: "Proposed improvement" 
    
